### ISSUE TITLE
Qlog draft 01

### ISSUE THREAD

**Issue by davidhassel** [quiclog/quictrace2qlog#3]
Qlog version needs to be updated. Uploading a proper qlog draft 01 to have it visualized does not work.

**Comment by rmarx** [comment]
Hello @davidhassel, thank you for the issue. 

Could you give a bit more details? Which version needs updating exactly? What error(s) do you get when uploading? What are you uploading exactly? I assume you're uploading to https://qvis.edm.uhasselt.be/?

Could you share an example file that produces errors?

**Comment by davidhassel** [comment]
Hello, sorry for the undetailed issue.

I used https://quic.edm.uhasselt.be/qtr-to-qlog/ (link from this git repo) to try and visualize a qlog file. According to the site I can upload a proper .qlog file just to have it visualized, but I guess that that demo is not updated anymore and qvis should be used for visualization.

Any demo file from aioquic (https://quic.aiortc.org/logs) should produce the error.

**Comment by rmarx** [comment]
Aha, ok, yes that makes sense :) 

This repository is a bit outdated; it was for a first iteration of our tools, which have "grown up" and now live at https://qvis.edm.uhasselt.be/. qvis should be fully compatible with the aioquic logs at that URL, though the quictrace format isn't really officially supported there anymore.

I assume you're not using quictrace and mainly want to visualize qlog files from aioquic? 

I'll update the README for this repo to make all this clearer. Thanks for opening the issue.

**Comment by davidhassel** [comment]
That is correct. Thanks for the update and quick response.
